HeartPredictor/urls.py
from django.contrib import admin
from django.urls import include, path
from predictor import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('predictor/', include('predictor.urls')),
    path('', views.index, name='Homepage'),
    path('predictHF', views.predictHF, name='predictHF'),
    path('updateDataBase', views.updateDataBase, name='updateDataBase'),
    
    path('dashboard_with_pivot/', views.dashboard_with_pivot, name='dashboard_with_pivot'),
    path('data', views.pivot_data, name='pivot_data'),

    # Django Auth
    path('accounts/login', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
]

predictor/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views


app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('predictHF',views.predictHF, name='predictHF'),
    path('updateDataBase',views.updateDataBase, name='updateDataBase'),
    #path('viewDataBase/',views.viewDataBase, name='viewDataBase'),
    path('dashboard_with_pivot/', views.dashboard_with_pivot, name='dashboard_with_pivot'),
    path('data', views.pivot_data, name='pivot_data'),
    path('accounts/login', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
]

predictor/models.py
from django.db import models

# Create your models here.


class prediction_data(models.Model):
    postcode = models.CharField(max_length=200, null=True, blank=True )
    country = models.CharField(max_length=200,  null=True, blank=True)
    gender = models.CharField(max_length=200)
    age = models.CharField(max_length=200)
    cigsPerDay = models.CharField(max_length=200)
    currentSmoker = models.CharField(max_length=200)
    prevalentHyp = models.CharField(max_length=200)
    totChol = models.CharField(max_length=200)
    sysBP = models.CharField(max_length=200)
    diaBP = models.CharField(max_length=200)
    bmi = models.CharField(max_length=200)
    heartRate = models.CharField(max_length=200)
    glucose = models.CharField(max_length=200)
    prediction = models.CharField(max_length=200)

predictor/views.py
from multiprocessing import context
from django.shortcuts import redirect, render
from .models import prediction_data
from django.contrib import messages
from django.core import serializers
from django.http import HttpResponseRedirect, JsonResponse

# Create your views here.

import sklearn.externals
import joblib
import pandas as pd

modelReload = joblib.load('./models/HeartModel.pkl')




def index(request):
    context = {'a': 'Hello world!'}
    return render(request, 'index.html', context)


def predictHF(request):
    # print(request)
    if request.method == 'POST':
        # print(request.POST.dict())
        temp = {}
        temp["gender"] = request.POST.get("genderVal")
        temp["age"] = request.POST.get("ageVal")
        temp["cigsPerDay"] = request.POST.get("cigsPerDayVal")
        temp["currentSmoker"] = request.POST.get("currentSmokerVal")
        temp["prevalentHyp"] = request.POST.get("prevalentHypVal")
        temp["totChol"] = request.POST.get("totCholVal")
        temp["sysBP"] = request.POST.get("sysBPVal")
        temp["diaBP"] = request.POST.get("diaBPVal")
        temp['BMI'] = request.POST.get("BMIVal")
        temp['heartRate'] = request.POST.get("heartRateVal")
        temp['glucose'] = request.POST.get("glucoseVal")
        print(temp)
    test_data = pd.DataFrame({'x': temp}).transpose()
    Prediction = modelReload.predict(test_data)[0]
    text1 = "Patient has a ten year risk of heart failure"
    text2 = "Congratulations! patient currently has no risk of heart failure "
    if Prediction == 1:
        context = {'Prediction': text1, 'temp': temp}
    else:
        context = {'Prediction': text2, 'temp': temp}
    return render(request, 'index.html', context)


def updateDataBase(request):
    data = prediction_data()
    data.gender = request.POST.get("genderVal")
    data.age = request.POST.get("ageVal")
    data.cigsPerDay = request.POST.get("cigsPerDayVal")
    data.currentSmoker = request.POST.get("currentSmokerVal")
    data.prevalentHyp = request.POST.get("prevalentHypVal")
    data.totChol = request.POST.get("totCholVal")
    data.sysBP = request.POST.get("sysBPVal")
    data.diaBP = request.POST.get("diaBPVal")
    data.bmi = request.POST.get("BMIVal")
    data.heartRate = request.POST.get("heartRateVal")
    data.glucose = request.POST.get("glucoseVal")
    data.postcode = request.POST.get("postcode")
    data.country = request.POST.get("country")

    text1 = "Patient has a ten year risk of heart failure"

    if request.POST.get("predictVal") == text1:
        data.prediction = 0
    else:
        data.prediction = 1
    
    data.save()
    report = messages.success(request, "Data added successfully")
    context = {'report': report}
    render(request, 'index.html', context)
    return redirect('Homepage')



def dashboard_with_pivot(request):
    return render(request, 'viewDB.html', {})


def pivot_data(request):
    dataset = prediction_data.objects.all()
    data = serializers.serialize('json', dataset)
    return JsonResponse(data, safe=False)

templates/accounts/login.html
{% extends 'headerPage.html' %}

{% block title %} Login {% endblock %}


{% block content%}

<h2>Login</h2>

<form method="post" enctype="multipart/form-data" action="">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Login</button>


</form>


{% endblock %}

templates/headerPage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

     <title>Heart Failure prediction usecase</title>

     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=Edge">
     <meta name="description" content="">
     <meta name="keywords" content="">
     <meta name="author" content="Tooplate">
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
     <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
     <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" >
     <link rel="stylesheet" href="{% static 'css/animate.css' %}" >
     <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" >
     <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}" >

     <!-- MAIN CSS -->

</head>
<body id="top" data-spy="scroll" data-target=".navbar-collapse" data-offset="50">

     <div class="container">
     <!-- MENU -->
     <header>
     <section class="navbar navbar-default navbar-static-top" role="navigation" style="align-items: center; color:black; background-color:rgb(207, 243, 193);">
          <div class="container">

               <div class="navbar-header">
                    <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                         <span class="icon icon-bar"></span>
                         <span class="icon icon-bar"></span>
                         <span class="icon icon-bar"></span>
                    </button>

                    <!-- lOGO TEXT HERE -->
                    <a href="/" class="navbar-brand"><i class="fa fa-h-square" style="font-weight: bolder;color: black;"></i>HFPredictor</a>
               </div>

               <!-- MENU LINKS -->
               <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                         <li><a href="/" class="smoothScroll" style="font-weight: bolder;color:chocolate;">Home</a></li>
                         <li><a href="{% url 'accounts:login' %}" class="smoothScroll" style="font-weight: bolder;color:chocolate;">Dashboard</a></li>
                    </ul>
               </div>

          </div>
     </section>
</header>
</div>


     <!-- HOME -->


<div class="container">
     {% block content%}
     {% endblock %}
    
</div>

     <!-- FOOTER -->
     <footer data-stellar-background-ratio="5">
          <div class="container">
               <div class="row">

                    

                    <div class="col-md-12 col-sm-12 border-top">
                         <div class="col-md-4 col-sm-6">
                              <div class="copyright-text"> 
                                   <p>Copyright </p>
                              </div>
                         </div>
                         <div class="col-md-6 col-sm-6">
                              <div class="footer-link"> 
                                   
                                   <a href="#"></a>
                              </div>
                         </div>
                         <div class="col-md-2 col-sm-2 text-align-center">
                              <div class="angle-up-btn"> 
                                  <a href="#top" class="smoothScroll wow fadeInUp" data-wow-delay="1.2s"><i class="fa fa-angle-up"></i></a>
                              </div>
                         </div>   
                    </div>
                    
               </div>
          </div>
     </footer>

     <!-- SCRIPTS -->
     <script  src="{% static 'js/jquery.js' %}"></script>
     <script  src="{% static 'js/bootstrap.min.js' %}"></script>
     <script  src="{% static 'js/jquery.sticky.js' %}"></script>
     <script  src="{% static 'js/jquery.stellar.min.js' %}"></script>
     <script  src="{% static 'js/wow.min.js' %}"></script>
     <script  src="{% static 'js/smoothscroll.js' %}"></script>
     <script  src="{% static 'js/owl.carousel.min.js' %}"></script>
     <script  src="{% static 'js/custom.js' %}"></script>

</body>
</html>

templates/index.html
{% extends 'headerPage.html' %}


{% block content%}

{{report}}
<h2 style="color: rgb(73, 125, 238);">Check risk of heart failure with this predictive model</h2>
<h3 style="color: chocolate;">Please enter details </h3>
<br>
<div style="color:black; background-color:rgb(207, 243, 193);">
    {% if Prediction %}
    <form method="post" enctype="multipart/form-data" action="updateDataBase">
        {% else %}
        <form method="post" enctype="multipart/form-data" action="predictHF">
            {% endif%}
            {% csrf_token %}

            <div class="col-md-4 col-sm-4">
                <label for="fname">Gender (Female/Male = 0/1):</label>
            </div>
            <select style="width: 4.7cm; height: 0.7cm;" name="genderVal" type="number" value={{temp.gender}}>
                <option>0</option>
                <option>1</option>
            </select><br><br>

            <div class="col-md-4 col-sm-4">
                <label for="fname">Age:</label>
            </div>
            <input name="ageVal" type="number" min="0" step="0.01" required aria-required="true" value={{temp.age}}
                required=""><br><br>


            <div class="col-md-4 col-sm-4">
                <label for="fname">Smoker? (No/Yes = 0/1):</label>
            </div>
            <select style="width: 4.7cm; height: 0.7cm;" type="number" id="fname" name="currentSmokerVal"
                value={{temp.currentSmoker}}>
                <option>0</option>
                <option>1</option>
            </select><br><br>

            <div class="col-md-4 col-sm-4">
                <label for="lname">cigarettes Per Day:</label>
            </div>
            <input type="number" min="0" step="0.01" id="lname" required aria-required="true" name="cigsPerDayVal"
                value={{temp.cigsPerDay}} required=""><br><br>

            <div class="col-md-4 col-sm-4">
                <label for="lname">Hypertensive? (No/Yes = 0/1):</label>
            </div>
            <select style="width: 4.7cm; height: 0.7cm;" type="number" id="lname" name="prevalentHypVal"
                value={{temp.prevalentHyp}}>
                <option>0</option>
                <option>1</option>
            </select><br><br>

            <div class="col-md-4 col-sm-4">
                <label for="fname">Blood Cholesterol (normal range: < 200mg/dl)</label>
            </div>
            <input type="number" min="0" step="0.01" id="fname" placeholder="mg/dl" required aria-required="true"
                name="totCholVal" value={{temp.totChol}} required=""><br><br>

            <div class="col-md-4 col-sm-4">
                <label for="lname">Systolic blood pressure (normal:< 120MmHg)</label>
            </div>
            <input type="number" min="0" step="0.01" id="lname" placeholder="MmHg" required aria-required="true"
                name="sysBPVal" value={{temp.sysBP}} required=""><br><br>

            <div class="col-md-4 col-sm-4">
                <label for="lname">Diastolic blood pressure (normal:< 80MmHg)</label>
            </div>
            <input type="number" min="0" step="0.01" id="lname" placeholder="MmHg" required aria-required="true"
                name="diaBPVal" value={{temp.diaBP}} required=""><br><br>

            <div class="col-md-4 col-sm-4">
                <label for="lname">Body Mass Index (normal range: 18.5-24.9 kg/m2)</label>
            </div>
            <input type="number" min="0" step="0.01" id="lname" placeholder="kg/m2" required aria-required="true"
                name="BMIVal" value={{temp.BMI}} required=""><br><br>

            <div class="col-md-4 col-sm-4">
                <label for="lname">Heart Rate (normal:60-100bpm)</label>
            </div>
            <input type="number" min="0" step="0.01" id="lname" placeholder="BPM" required aria-required="true"
                name="heartRateVal" value={{temp.heartRate}} required=""><br><br>


            <div class="col-md-4 col-sm-4">
                <label for="lname">Blood glucose (normal: 72-99mg/dl fasting) </label>
            </div>
            <input type="number" min="0" step="0.01" id="lname" placeholder="mg/dl" required aria-required="true"
                name="glucoseVal" value={{temp.glucose}} required=""><br><br>

            {% if Prediction %}
            <div style="padding: 10px; border-style: double;">
                <div class="container"
                    style="border: 5px;font-family: Verdana, Geneva, Tahoma, sans-serif;color: black;font-weight: bold;">
                    Score: {{Prediction}}
                </div>

                <input type="hidden" id="lname" name="predictVal" value={{Prediction}}>
                <br>
                <div class="container"
                    style="border: 2cm;font-family: Verdana, Geneva, Tahoma, sans-serif;color: chocolate;">
                    This data helps in public health decision making,
                    please enter postcode and country if you would like to contribute this data. <br>
                    you can also submit your score without entering postcode and/or country.
                </div>
                <br>
                <div class="col-md-4 col-sm-4">
                    <label for="lname">Postcode</label>
                </div>
                <input type="text" id="lname" name="postcode" value={{temp.postcode}}><br><br>
                <div class="col-md-4 col-sm-4">
                    <label for="lname">Country</label>
                </div>
                <input type="text" id="lname" name="country" value={{temp.country}}> <br><br>
                <div>
                    <input type="submit" value="Submit" class="btn btn-primary">
                    <input type="button" onclick="window.location.href ='/';" value="Decline" class="btn btn-danger">
                </div>
            </div>
            {% else%}
            <input type="submit" value="submit" class="btn btn-primary">
            {% endif %}

        </form>
    </form>
</div>
{% endblock %}

templates/viewDB.html
{% extends 'headerPage.html' %}


{% block content%}

<head>
    <meta charset="UTF-8">
    <title>Dashboard</title>
    <script src="https://cdn.flexmonster.com/flexmonster.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.flexmonster.com/theme/stripedteal/flexmonster.min.css">
    
</head>

<body>
    <div id="grid-table"></div>
    <div id="pivot-table-container" data-url="{% url 'pivot_data' %}"></div>
    <div id="pivot-chart-container"></div>
    <script>
        function processData(dataset) {
            var result = []
            dataset = JSON.parse(dataset);
            dataset.forEach(item => result.push(item.fields));
            return result;
        }
        $.ajax({
            url: $("#pivot-table-container").attr("data-url"),
            dataType: 'json',
            success: function (data) {
                new Flexmonster({
                    container: "#pivot-table-container",
                    componentFolder: "https://cdn.flexmonster.com/",
                    width: "100%",
                    height: 430,
                    //toolbar: true,
                    report: {
                        dataSource: {
                            type: "json",
                            data: processData(data),

                        },

                    }
                });
                new Flexmonster({
                    container: "#pivot-chart-container",
                    componentFolder: "https://cdn.flexmonster.com/",
                    width: "100%",
                    height: 430,
                    //toolbar: true,
                    report: {
                        dataSource: {
                            type: "json",
                            data: processData(data),

                        },

                        "options": {
                            "viewType": "charts",
                            "chart": {
                                "type": "bar"
                            }
                        }
                    }
                });

                new Flexmonster({
                    container: "#grid-table",
                    componentFolder: "https://cdn.flexmonster.com/",
                    width: "100%",
                    height: 430,
                    //toolbar: true,
                    report: {
                        dataSource: {
                            type: "json",
                            data: processData(data),

                        },

                        options: {
                            grid: {
                                type: "flat"
                            },
                            configuratorActive: false
                        },
                    }
                });


            }
        });


    </script>
</body>

{% endblock %}